alter table app_users
add column if not exists last_login timestamptz;

create table if not exists events (
    id bigint generated by default as identity primary key,
    event_name text not null,
    app_user_id uuid references app_users(id) on delete set null,
    phone_number text,
    created_at timestamptz not null default now()
);

create index if not exists events_event_name_idx on events(event_name);
create index if not exists events_app_user_id_idx on events(app_user_id);
create index if not exists events_phone_number_idx on events(phone_number);
create index if not exists events_created_at_idx on events(created_at);
