create extension if not exists pgcrypto;

create table if not exists app_users (
    id uuid primary key default gen_random_uuid(),
    phone_number text unique not null,
    pin_hash text not null,
    pin_salt text not null,
    failed_attempts integer not null default 0,
    locked_until timestamptz,
    is_admin boolean not null default false,
    last_login timestamptz,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists transactions (
    id bigint generated by default as identity primary key,
    app_user_id uuid not null references app_users(id) on delete cascade,
    phone_number text not null,
    transaction_date date not null,
    network text not null,
    transaction_type text not null,
    amount numeric not null,
    note text,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index if not exists transactions_app_user_id_idx on transactions(app_user_id);
create index if not exists transactions_phone_number_idx on transactions(phone_number);
create index if not exists transactions_transaction_date_idx on transactions(transaction_date);

create table if not exists events (
    id bigint generated by default as identity primary key,
    event_name text not null,
    app_user_id uuid references app_users(id) on delete set null,
    phone_number text,
    created_at timestamptz not null default now()
);

create index if not exists events_event_name_idx on events(event_name);
create index if not exists events_app_user_id_idx on events(app_user_id);
create index if not exists events_phone_number_idx on events(phone_number);
create index if not exists events_created_at_idx on events(created_at);

-- Prototype note:
-- This custom App PIN login is for MVP testing. Before public launch, add stricter database policies,
-- move PIN verification to a server-side function, or use Supabase Auth / Edge Functions.
